#! /usr/bin/env python

target = 'wldumper'

def options(ctx):
	ctx.load('compiler_cxx')


def configure(ctx):
	ctx.load('compiler_cxx')


def build(bld):
	print('Building ' + target)
	source_files = bld.path.ant_glob('*.cpp')
	bld.program(source=source_files, target=target, use=['base'])
