#! /usr/bin/env python

target = 'wlanalyzer'

def options(opt):
	opt.load('compiler_cxx qt5')


def configure(ctx):
	ctx.load('compiler_cxx qt5')


def build(bld):
	source_files = bld.path.ant_glob('*.cpp')
	ui_files = bld.path.ant_glob('*.ui')
	bld(source = source_files + ui_files, target='wlanalyzer', features='qt5 cxx cxxprogram', use = [ 'QT5CORE', 'QT5GUI', 'QT5WIDGETS', 'QT5NETWORK', 'wlanalyzer_base' ], includes = [ bld.path.get_bld(), bld.path.get_src() ])

