#! /usr/bin/env python

def options(opt):
	opt.recurse('base')
	opt.recurse('dumper')
	opt.recurse('analyzer')


def configure(ctx):
	ctx.recurse('base')
	ctx.recurse('dumper')
	if ctx.options.analyzer:
		ctx.recurse('analyzer')


def build(bld):
	bld.recurse('base')
	bld.recurse('dumper')
	if bld.options.analyzer:
		bld.recurse('analyzer')
