#! /usr/bin/env python

def options(opt):
	opt.recurse('wlanalyzer_base')
	opt.recurse('dumper')
	opt.recurse('analyzer')


def configure(ctx):
	ctx.recurse('wlanalyzer_base')
	ctx.recurse('dumper')
	if ctx.env.analyzer:
		ctx.recurse('analyzer')


def build(bld):
	bld.recurse('wlanalyzer_base')
	bld.recurse('dumper')
	if bld.env.analyzer:
		bld.recurse('analyzer')
